### ISSUE TITLE
pip install fails to add ".p" files on version 0.7

### ISSUE THREAD

**Issue by codez266** [kevincobain2000/sentiment_classifier#10]
pip install fails to add ".p" files on version 0.7 which leads to the error:

`"FileNotFoundError: [Errno 2] No such file or directory: '...lib/python3.6/site-packages/senti_classifier/data/SentiWn.p'"`

On downloading the latest build from https://pypi.python.org/pyp... and extracting, the "src/senti_classifier/data/" directory is missing the ".p" files. PyPi needs update.

**Comment by codez266** [comment]
Duplicate of https://github.com/kevincobain2000/sentiment_classifier/issues/9

**Comment by ttpro1995** [comment]
I do not see .p file /sentiment_classifier-0.7/src/senti_classifier/data

**Comment by kevincobain2000** [comment]
Please install it from github. Pickle didn't get distributed somehow. Will update on the latest 0.8. Or pull requests welcome

https://github.com/kevincobain2000/sentiment_classifier/tree/master/src/senti_classifier/data
