### ISSUE TITLE
Getting 0,0 score after pulling the latest code from current branch

### ISSUE THREAD

**Issue by prasadpande1990** [kevincobain2000/sentiment_classifier#3]
Hi,

I am using sentiment_classifier in my project. I installed and importing in my script. but for all sentences it is getting 0,0 scores. I referred to last issue and verified if code version is latest and it is.

Can you help.

Attaching code and screenshot:

Code: 
pos_score, neg_score = senti_classifier.polarity_scores('The movie was the worst movie')
print("Positive Score")
print(pos_score)
print("Negative Score")
print(neg_score)

Screenshot:
![capture_senti](https://cloud.githubusercontent.com/assets/8678175/7334115/58dfa354-eb4e-11e4-966a-3bc8333cd4d6.JPG)

**Comment by kevincobain2000** [comment]
I haven't had problems with the latest pip install, lets wait for a while if the other users from #1 can confirm it

**Comment by prasadpande1990** [comment]
Closing this issue. It is working for me now.

I was referring to the wrong senti_classifier package which and not the one in ~/src/ directory. 

Thanks

**Comment by kevincobain2000** [comment]
:+1: awesome all the best with your project !

**Comment by oaraque** [comment]
Hello,
I have observed that the call to polarity_scores differs if you pass a list of sentences or a single string:

```
In [1]: from senti_classifier import senti_classifier

In [2]: senti_classifier.polarity_scores('My dog is happy')                                                                                                                                            
Out[2]: (0.0, 0.0)

In [3]: senti_classifier.polarity_scores(['My dog is happy'])
Out[3]: (0.625, 0.125)
```

Maybe that is the problem sometimes.
