### ISSUE TITLE
Any Python 3 support?

### ISSUE THREAD

**Issue by MrLokans** [kevincobain2000/sentiment_classifier#4]
It is currently impossible to analyze text with python 3, will it be difficult to adopt code for the third version of python?

**Comment by kevincobain2000** [comment]
well the classifier depends on nltk and as it uses its dictionary. Parser for senti wordnet SentiWordNetCorpusReader  in this lib is not that big , so i don't think it should take time to translate to python 3.

mostly now I work on php, and have been out of touch on version changes on python. migration from 2.7 -> 3.0 might take me a while. Feel free to submit a pull request tho.

https://github.com/kevincobain2000/sentiment_classifier/blob/master/src/senti_classifier/senti_classifier.py

**Comment by MrLokans** [comment]
OK, I will take a look into the source code and will try to make it python 2 and 3 compatible and will send the PR in a couple of days.

**Comment by MrLokans** [comment]
Just created a [PR](https://github.com/kevincobain2000/sentiment_classifier/pull/5)
