### ISSUE TITLE
Adding Acronyms in senti_classifer

### ISSUE THREAD

**Issue by harshalchopde** [kevincobain2000/sentiment_classifier#7]
Tried senti_classifier on some data to get sentiments of the sentences. It  working fine for me. I still have two queries

1. It doesn't  work for acronyms, Curious to know how can we add some acronyms in the dictionary of this algorithm.
2. Also, is there any way where it can handle negation?

Can you please let me know how can i overcome these? I am completely stuck at this point.

**Comment by kevincobain2000** [comment]
Both can improve the performance drastically.

This classifier is untrained. One way I would do is to handle ACRONYMS and negation separately using statistical classifiers. For negation especially, you can use a simple bigrams model and train a naive bayes.

https://github.com/kevincobain2000/sentiment_classifier/blob/master/src/senti_classifier/classifiers.py#L63-L72


>how can we add some acronyms in the dictionary of this algorithm.

That is actually a good idea, it'd be upto the creators of sentiWN http://sentiwordnet.isti.cnr.it/
or alternatively you can append data to this project and update the pickle by recalling the class SentiWordNetCorpusReader

https://github.com/kevincobain2000/sentiment_classifier/blob/master/src/senti_classifier/senti_classifier.py#L227

**Comment by harshalchopde** [comment]
Thanks a lot!!! Will try this out soon.
